[project]
name = "lecture-1"
version = "0.1.0"
description = "first task"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6"
]
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

